// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.36.1
// source: marketstream.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakerMessageType int32

const (
	MakerMessageType_MAKER_MESSAGE_TYPE_UNSPECIFIED    MakerMessageType = 0
	MakerMessageType_MAKER_MESSAGE_TYPE_FRAME_PUSH     MakerMessageType = 1 // Maker -> Marketstream
	MakerMessageType_MAKER_MESSAGE_TYPE_FRAME_ACK      MakerMessageType = 2 // Marketstream -> Maker
	MakerMessageType_MAKER_MESSAGE_TYPE_HEARTBEAT      MakerMessageType = 3 // Bidirectional
	MakerMessageType_MAKER_MESSAGE_TYPE_CONNECTION_ACK MakerMessageType = 5 // Marketstream -> Maker
)

// Enum value maps for MakerMessageType.
var (
	MakerMessageType_name = map[int32]string{
		0: "MAKER_MESSAGE_TYPE_UNSPECIFIED",
		1: "MAKER_MESSAGE_TYPE_FRAME_PUSH",
		2: "MAKER_MESSAGE_TYPE_FRAME_ACK",
		3: "MAKER_MESSAGE_TYPE_HEARTBEAT",
		5: "MAKER_MESSAGE_TYPE_CONNECTION_ACK",
	}
	MakerMessageType_value = map[string]int32{
		"MAKER_MESSAGE_TYPE_UNSPECIFIED":    0,
		"MAKER_MESSAGE_TYPE_FRAME_PUSH":     1,
		"MAKER_MESSAGE_TYPE_FRAME_ACK":      2,
		"MAKER_MESSAGE_TYPE_HEARTBEAT":      3,
		"MAKER_MESSAGE_TYPE_CONNECTION_ACK": 5,
	}
)

func (x MakerMessageType) Enum() *MakerMessageType {
	p := new(MakerMessageType)
	*p = x
	return p
}

func (x MakerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MakerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_marketstream_proto_enumTypes[0].Descriptor()
}

func (MakerMessageType) Type() protoreflect.EnumType {
	return &file_marketstream_proto_enumTypes[0]
}

func (x MakerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MakerMessageType.Descriptor instead.
func (MakerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{0}
}

type RouterMessageType int32

const (
	RouterMessageType_ROUTER_MESSAGE_TYPE_UNSPECIFIED    RouterMessageType = 0
	RouterMessageType_ROUTER_MESSAGE_TYPE_SUBSCRIBE      RouterMessageType = 1 // Router -> Marketstream
	RouterMessageType_ROUTER_MESSAGE_TYPE_SUBSCRIBE_ACK  RouterMessageType = 3 // Marketstream -> Router
	RouterMessageType_ROUTER_MESSAGE_TYPE_FRAME_UPDATE   RouterMessageType = 5 // Marketstream -> Router
	RouterMessageType_ROUTER_MESSAGE_TYPE_HEARTBEAT      RouterMessageType = 6 // Bidirectional
	RouterMessageType_ROUTER_MESSAGE_TYPE_ERROR          RouterMessageType = 7
	RouterMessageType_ROUTER_MESSAGE_TYPE_CONNECTION_ACK RouterMessageType = 8 // Marketstream -> Router
)

// Enum value maps for RouterMessageType.
var (
	RouterMessageType_name = map[int32]string{
		0: "ROUTER_MESSAGE_TYPE_UNSPECIFIED",
		1: "ROUTER_MESSAGE_TYPE_SUBSCRIBE",
		3: "ROUTER_MESSAGE_TYPE_SUBSCRIBE_ACK",
		5: "ROUTER_MESSAGE_TYPE_FRAME_UPDATE",
		6: "ROUTER_MESSAGE_TYPE_HEARTBEAT",
		7: "ROUTER_MESSAGE_TYPE_ERROR",
		8: "ROUTER_MESSAGE_TYPE_CONNECTION_ACK",
	}
	RouterMessageType_value = map[string]int32{
		"ROUTER_MESSAGE_TYPE_UNSPECIFIED":    0,
		"ROUTER_MESSAGE_TYPE_SUBSCRIBE":      1,
		"ROUTER_MESSAGE_TYPE_SUBSCRIBE_ACK":  3,
		"ROUTER_MESSAGE_TYPE_FRAME_UPDATE":   5,
		"ROUTER_MESSAGE_TYPE_HEARTBEAT":      6,
		"ROUTER_MESSAGE_TYPE_ERROR":          7,
		"ROUTER_MESSAGE_TYPE_CONNECTION_ACK": 8,
	}
)

func (x RouterMessageType) Enum() *RouterMessageType {
	p := new(RouterMessageType)
	*p = x
	return p
}

func (x RouterMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouterMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_marketstream_proto_enumTypes[1].Descriptor()
}

func (RouterMessageType) Type() protoreflect.EnumType {
	return &file_marketstream_proto_enumTypes[1]
}

func (x RouterMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouterMessageType.Descriptor instead.
func (RouterMessageType) EnumDescriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{1}
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping bool `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Pong bool `protobuf:"varint,2,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetPing() bool {
	if x != nil {
		return x.Ping
	}
	return false
}

func (x *Heartbeat) GetPong() bool {
	if x != nil {
		return x.Pong
	}
	return false
}

type PairKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId    uint64 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	PairId     uint32 `protobuf:"varint,2,opt,name=pairId,proto3" json:"pairId,omitempty"`
	BaseToken  string `protobuf:"bytes,3,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken string `protobuf:"bytes,4,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
}

func (x *PairKey) Reset() {
	*x = PairKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairKey) ProtoMessage() {}

func (x *PairKey) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairKey.ProtoReflect.Descriptor instead.
func (*PairKey) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{1}
}

func (x *PairKey) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PairKey) GetPairId() uint32 {
	if x != nil {
		return x.PairId
	}
	return 0
}

func (x *PairKey) GetBaseToken() string {
	if x != nil {
		return x.BaseToken
	}
	return ""
}

func (x *PairKey) GetQuoteToken() string {
	if x != nil {
		return x.QuoteToken
	}
	return ""
}

type PriceLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Human-readable decimal price in quote tokens per base token, converted
	// using both tokens' decimals rather than expressed in native token units.
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Human-readable decimal amount in base tokens, converted using the base
	// token's decimals.
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{2}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// CompactFrame contains the three raw bytes32 slots used by the contract.
// These fields are signed. Marketstream forwards them unchanged from Maker
// to Router so that repacking cannot invalidate the signature.
type CompactFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`       // Raw bytes32 header in the contract's packed format.
	BidLevels []byte `protobuf:"bytes,2,opt,name=bidLevels,proto3" json:"bidLevels,omitempty"` // bytes32; five 48-bit levels: offset (24) | qtyLots (24).
	AskLevels []byte `protobuf:"bytes,3,opt,name=askLevels,proto3" json:"askLevels,omitempty"` // bytes32; the same layout as bidLevels.
}

func (x *CompactFrame) Reset() {
	*x = CompactFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompactFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactFrame) ProtoMessage() {}

func (x *CompactFrame) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactFrame.ProtoReflect.Descriptor instead.
func (*CompactFrame) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{3}
}

func (x *CompactFrame) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CompactFrame) GetBidLevels() []byte {
	if x != nil {
		return x.BidLevels
	}
	return nil
}

func (x *CompactFrame) GetAskLevels() []byte {
	if x != nil {
		return x.AskLevels
	}
	return nil
}

// Maker supplies the complete MarketFrame, including its human-readable prices
// and amounts. Marketstream validates these values without deriving missing
// fields or modifying the signed frame. Router can read the prices and amounts
// without decoding the packed header or levels.
//
// Only decoded fields needed by Router are included. Maker converts baseTick
// and the packed levels into bids and asks; Marketstream reads baseTick directly
// from frame.header when validating them. The majorVersion and minorVersion
// values also remain in frame.header and are decoded there for version checks.
//
// The contract sets bidFilledLots, askFilledLots, and writtenAt when frames are
// written or trades execute on-chain. These fields are zero in signed calldata
// and are not forwarded separately. Filled-lot counters persist within a major
// version, so Maker must account for on-chain fills before declaring executable
// depth in bids and asks. Maker tracks fills and manages inventory independently
// of Marketstream.
type MarketFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Must match updatedAt in frame.header. Router combines this timestamp with
	// the current time and global decay parameters obtained separately from
	// pair metadata to calculate current decayed prices.
	UpdatedAt uint32 `protobuf:"varint,1,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// pairId must match the uint32 pairId encoded in frame.header.
	Pair *PairKey `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	// Bids in descending price order, with decimal prices and amounts describing
	// executable depth after Maker's inventory checks.
	Bids []*PriceLevel `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	// Asks in ascending price order, with the same depth semantics as bids.
	Asks []*PriceLevel `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	// Original signed header and levels, used by Router for on-chain submission.
	Frame *CompactFrame `protobuf:"bytes,5,opt,name=frame,proto3" json:"frame,omitempty"`
	// Ethereum maker contract address associated with the authenticated Maker
	// identity on this chain. Signature verification recovers the registered
	// frameSigner() EOA, not the maker contract address, using local ECDSA
	// recovery and comparison. Marketstream does not use ERC-1271 or make an
	// on-chain call to verify the signature.
	//
	// Maker -> Marketstream preserves the claimed address's original spelling;
	// Marketstream normalizes it only for comparison. Marketstream -> Router
	// replaces this field with the trusted address confirmed during validation,
	// normalized to lowercase.
	MakerAddr string `protobuf:"bytes,6,opt,name=makerAddr,proto3" json:"makerAddr,omitempty"`
	// Exactly 65 bytes in r||s||v wire form. Local ECDSA recovery must match
	// the frameSigner() currently registered for makerAddr.
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *MarketFrame) Reset() {
	*x = MarketFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketFrame) ProtoMessage() {}

func (x *MarketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketFrame.ProtoReflect.Descriptor instead.
func (*MarketFrame) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{4}
}

func (x *MarketFrame) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *MarketFrame) GetPair() *PairKey {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *MarketFrame) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *MarketFrame) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *MarketFrame) GetFrame() *CompactFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *MarketFrame) GetMakerAddr() string {
	if x != nil {
		return x.MakerAddr
	}
	return ""
}

func (x *MarketFrame) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MakerEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MakerMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=marketstream.v1.MakerMessageType" json:"type,omitempty"`
	// Unix milliseconds when Maker or Marketstream sent this message. Used only
	// for observation and logging. Freshness validation uses MarketFrame.updatedAt
	// and the global maxAge parameter instead.
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*MakerEnvelope_FramePush
	//	*MakerEnvelope_FrameAck
	//	*MakerEnvelope_Heartbeat
	//	*MakerEnvelope_ConnectionAck
	Payload isMakerEnvelope_Payload `protobuf_oneof:"payload"`
}

func (x *MakerEnvelope) Reset() {
	*x = MakerEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakerEnvelope) ProtoMessage() {}

func (x *MakerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakerEnvelope.ProtoReflect.Descriptor instead.
func (*MakerEnvelope) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{5}
}

func (x *MakerEnvelope) GetType() MakerMessageType {
	if x != nil {
		return x.Type
	}
	return MakerMessageType_MAKER_MESSAGE_TYPE_UNSPECIFIED
}

func (x *MakerEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (m *MakerEnvelope) GetPayload() isMakerEnvelope_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *MakerEnvelope) GetFramePush() *MarketFrame {
	if x, ok := x.GetPayload().(*MakerEnvelope_FramePush); ok {
		return x.FramePush
	}
	return nil
}

func (x *MakerEnvelope) GetFrameAck() *FrameAck {
	if x, ok := x.GetPayload().(*MakerEnvelope_FrameAck); ok {
		return x.FrameAck
	}
	return nil
}

func (x *MakerEnvelope) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*MakerEnvelope_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *MakerEnvelope) GetConnectionAck() *ConnectionAck {
	if x, ok := x.GetPayload().(*MakerEnvelope_ConnectionAck); ok {
		return x.ConnectionAck
	}
	return nil
}

type isMakerEnvelope_Payload interface {
	isMakerEnvelope_Payload()
}

type MakerEnvelope_FramePush struct {
	FramePush *MarketFrame `protobuf:"bytes,3,opt,name=frame_push,json=framePush,proto3,oneof"`
}

type MakerEnvelope_FrameAck struct {
	FrameAck *FrameAck `protobuf:"bytes,4,opt,name=frame_ack,json=frameAck,proto3,oneof"` // Marketstream -> Maker; rejection only.
}

type MakerEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

type MakerEnvelope_ConnectionAck struct {
	ConnectionAck *ConnectionAck `protobuf:"bytes,7,opt,name=connection_ack,json=connectionAck,proto3,oneof"`
}

func (*MakerEnvelope_FramePush) isMakerEnvelope_Payload() {}

func (*MakerEnvelope_FrameAck) isMakerEnvelope_Payload() {}

func (*MakerEnvelope_Heartbeat) isMakerEnvelope_Payload() {}

func (*MakerEnvelope_ConnectionAck) isMakerEnvelope_Payload() {}

// Sent only when a frame is rejected. accepted is always false; successful
// frames do not receive an acknowledgement.
type FrameAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair *PairKey `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	// Frame versions are ordered lexicographically by (majorVersion, minorVersion).
	MajorVersion uint32 `protobuf:"varint,2,opt,name=majorVersion,proto3" json:"majorVersion,omitempty"`
	MinorVersion uint32 `protobuf:"varint,3,opt,name=minorVersion,proto3" json:"minorVersion,omitempty"` // A uint8 contract value represented as uint32.
	Accepted     bool   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectStep   string `protobuf:"bytes,5,opt,name=reject_step,json=rejectStep,proto3" json:"reject_step,omitempty"` // Identifier of the failed validation step.
	// Human-readable reason for rejection. Does not disclose trusted internal
	// state, such as the expected address.
	RejectReason string `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
}

func (x *FrameAck) Reset() {
	*x = FrameAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameAck) ProtoMessage() {}

func (x *FrameAck) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameAck.ProtoReflect.Descriptor instead.
func (*FrameAck) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{6}
}

func (x *FrameAck) GetPair() *PairKey {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *FrameAck) GetMajorVersion() uint32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *FrameAck) GetMinorVersion() uint32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *FrameAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FrameAck) GetRejectStep() string {
	if x != nil {
		return x.RejectStep
	}
	return ""
}

func (x *FrameAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// ConnectionAck is shared by Maker and Router connections. For Maker, identity
// is the stable makerId bound to the authenticated connection. A Maker may use
// different contract addresses on different chains, so this identifier is not
// an on-chain address. Router connections leave identity empty.
type ConnectionAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Identity   string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	ServerTime int64  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
}

func (x *ConnectionAck) Reset() {
	*x = ConnectionAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAck) ProtoMessage() {}

func (x *ConnectionAck) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionAck.ProtoReflect.Descriptor instead.
func (*ConnectionAck) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionAck) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ConnectionAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type RouterEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RouterMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=marketstream.v1.RouterMessageType" json:"type,omitempty"`
	// Unix milliseconds when Router or Marketstream sent this message.
	// Used only for observation and logging, as in MakerEnvelope.timestamp.
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*RouterEnvelope_Subscribe
	//	*RouterEnvelope_SubscribeAck
	//	*RouterEnvelope_Update
	//	*RouterEnvelope_Heartbeat
	//	*RouterEnvelope_Error
	//	*RouterEnvelope_ConnectionAck
	Payload isRouterEnvelope_Payload `protobuf_oneof:"payload"`
}

func (x *RouterEnvelope) Reset() {
	*x = RouterEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterEnvelope) ProtoMessage() {}

func (x *RouterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterEnvelope.ProtoReflect.Descriptor instead.
func (*RouterEnvelope) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{8}
}

func (x *RouterEnvelope) GetType() RouterMessageType {
	if x != nil {
		return x.Type
	}
	return RouterMessageType_ROUTER_MESSAGE_TYPE_UNSPECIFIED
}

func (x *RouterEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (m *RouterEnvelope) GetPayload() isRouterEnvelope_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *RouterEnvelope) GetSubscribe() *SubscribeRequest {
	if x, ok := x.GetPayload().(*RouterEnvelope_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (x *RouterEnvelope) GetSubscribeAck() *SubscribeAck {
	if x, ok := x.GetPayload().(*RouterEnvelope_SubscribeAck); ok {
		return x.SubscribeAck
	}
	return nil
}

func (x *RouterEnvelope) GetUpdate() *MarketFrame {
	if x, ok := x.GetPayload().(*RouterEnvelope_Update); ok {
		return x.Update
	}
	return nil
}

func (x *RouterEnvelope) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*RouterEnvelope_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *RouterEnvelope) GetError() *Error {
	if x, ok := x.GetPayload().(*RouterEnvelope_Error); ok {
		return x.Error
	}
	return nil
}

func (x *RouterEnvelope) GetConnectionAck() *ConnectionAck {
	if x, ok := x.GetPayload().(*RouterEnvelope_ConnectionAck); ok {
		return x.ConnectionAck
	}
	return nil
}

type isRouterEnvelope_Payload interface {
	isRouterEnvelope_Payload()
}

type RouterEnvelope_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type RouterEnvelope_SubscribeAck struct {
	SubscribeAck *SubscribeAck `protobuf:"bytes,5,opt,name=subscribe_ack,json=subscribeAck,proto3,oneof"`
}

type RouterEnvelope_Update struct {
	Update *MarketFrame `protobuf:"bytes,8,opt,name=update,proto3,oneof"`
}

type RouterEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,9,opt,name=heartbeat,proto3,oneof"`
}

type RouterEnvelope_Error struct {
	Error *Error `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

type RouterEnvelope_ConnectionAck struct {
	ConnectionAck *ConnectionAck `protobuf:"bytes,11,opt,name=connection_ack,json=connectionAck,proto3,oneof"`
}

func (*RouterEnvelope_Subscribe) isRouterEnvelope_Payload() {}

func (*RouterEnvelope_SubscribeAck) isRouterEnvelope_Payload() {}

func (*RouterEnvelope_Update) isRouterEnvelope_Payload() {}

func (*RouterEnvelope_Heartbeat) isRouterEnvelope_Payload() {}

func (*RouterEnvelope_Error) isRouterEnvelope_Payload() {}

func (*RouterEnvelope_ConnectionAck) isRouterEnvelope_Payload() {}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PairFilter selects pairs and makers independently; either selector may be
// omitted. A pair or maker in gray rollout is excluded unless its corresponding
// allow flag is explicitly true. Setting a selector alone does not grant access
// to gray rollout data.
//
// Setting allowPairGray to true requires an explicit pair; setting allowMakerGray
// to true requires an explicit maker. Invalid combinations are rejected in
// SubscribeAck.results.
type PairFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair           *PairKey `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`                      // Omitted means no pair restriction.
	Maker          string   `protobuf:"bytes,2,opt,name=maker,proto3" json:"maker,omitempty"`                    // Empty means no maker restriction.
	AllowPairGray  bool     `protobuf:"varint,3,opt,name=allowPairGray,proto3" json:"allowPairGray,omitempty"`   // Includes the specified pair during gray rollout.
	AllowMakerGray bool     `protobuf:"varint,4,opt,name=allowMakerGray,proto3" json:"allowMakerGray,omitempty"` // Includes the specified maker during gray rollout.
}

func (x *PairFilter) Reset() {
	*x = PairFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairFilter) ProtoMessage() {}

func (x *PairFilter) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairFilter.ProtoReflect.Descriptor instead.
func (*PairFilter) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{10}
}

func (x *PairFilter) GetPair() *PairKey {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *PairFilter) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *PairFilter) GetAllowPairGray() bool {
	if x != nil {
		return x.AllowPairGray
	}
	return false
}

func (x *PairFilter) GetAllowMakerGray() bool {
	if x != nil {
		return x.AllowMakerGray
	}
	return false
}

// Replaces the connection's complete subscription with these filters. The first
// request establishes the initial subscription; later requests replace it.
// Empty filters subscribe to all pairs and makers outside gray rollout.
// To stop receiving all updates, disconnect; empty filters do not unsubscribe.
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters []*PairFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeRequest) GetFilters() []*PairFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PairFilterResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *PairFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Ok     bool        `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string      `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *PairFilterResult) Reset() {
	*x = PairFilterResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairFilterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairFilterResult) ProtoMessage() {}

func (x *PairFilterResult) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairFilterResult.ProtoReflect.Descriptor instead.
func (*PairFilterResult) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{12}
}

func (x *PairFilterResult) GetFilter() *PairFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *PairFilterResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PairFilterResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SubscribeAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*PairFilterResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // One result per filter in this request.
}

func (x *SubscribeAck) Reset() {
	*x = SubscribeAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketstream_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAck) ProtoMessage() {}

func (x *SubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_marketstream_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAck.ProtoReflect.Descriptor instead.
func (*SubscribeAck) Descriptor() ([]byte, []int) {
	return file_marketstream_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeAck) GetResults() []*PairFilterResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_marketstream_proto protoreflect.FileDescriptor

var file_marketstream_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0x33, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x79, 0x0a, 0x07, 0x50, 0x61,
	0x69, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x69, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x70, 0x61, 0x69, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3a, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x62, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x64,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x69,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x73, 0x6b, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x73, 0x6b, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x73, 0x22, 0xac, 0x02, 0x0a, 0x0b, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x70, 0x61, 0x69,
	0x72, 0x12, 0x2f, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x62, 0x69,
	0x64, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x61,
	0x73, 0x6b, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6b, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0xed, 0x02, 0x0a, 0x0d, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3d, 0x0a, 0x0a, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x12, 0x38, 0x0a, 0x09, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x41, 0x63, 0x6b, 0x12, 0x3a, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x12, 0x47, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0xe2, 0x01, 0x0a, 0x08, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x41, 0x63,
	0x6b, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x74,
	0x65, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74,
	0x53, 0x74, 0x65, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0xe7, 0x03, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x41, 0x0a, 0x09, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x44, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x41, 0x63, 0x6b, 0x12, 0x36, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x47, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x48,
	0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x35, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61,
	0x69, 0x72, 0x47, 0x72, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x50, 0x61, 0x69, 0x72, 0x47, 0x72, 0x61, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x47, 0x72, 0x61, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x47,
	0x72, 0x61, 0x79, 0x22, 0x49, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x6f,
	0x0a, 0x10, 0x50, 0x61, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x4b, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x63, 0x6b, 0x12,
	0x3b, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x2a, 0xc4, 0x01, 0x0a,
	0x10, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x22, 0x0a, 0x1e, 0x4d, 0x41, 0x4b, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x4d, 0x41, 0x4b, 0x45, 0x52, 0x5f, 0x4d,
	0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x52, 0x41, 0x4d,
	0x45, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x41, 0x4b, 0x45,
	0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46,
	0x52, 0x41, 0x4d, 0x45, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x41,
	0x4b, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x03, 0x12, 0x25, 0x0a, 0x21,
	0x4d, 0x41, 0x4b, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43,
	0x4b, 0x10, 0x05, 0x2a, 0x92, 0x02, 0x0a, 0x11, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x52, 0x4f, 0x55,
	0x54, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21,
	0x0a, 0x1d, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10,
	0x01, 0x12, 0x25, 0x0a, 0x21, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49,
	0x42, 0x45, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x03, 0x12, 0x24, 0x0a, 0x20, 0x52, 0x4f, 0x55, 0x54,
	0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x05, 0x12, 0x21,
	0x0a, 0x1d, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10,
	0x06, 0x12, 0x1d, 0x0a, 0x19, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x07,
	0x12, 0x26, 0x0a, 0x22, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x08, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x61, 0x6b, 0x61, 0x70, 0x75, 0x2d, 0x4c, 0x61,
	0x62, 0x73, 0x2f, 0x74, 0x61, 0x6b, 0x61, 0x70, 0x75, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_marketstream_proto_rawDescOnce sync.Once
	file_marketstream_proto_rawDescData = file_marketstream_proto_rawDesc
)

func file_marketstream_proto_rawDescGZIP() []byte {
	file_marketstream_proto_rawDescOnce.Do(func() {
		file_marketstream_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketstream_proto_rawDescData)
	})
	return file_marketstream_proto_rawDescData
}

var file_marketstream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_marketstream_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_marketstream_proto_goTypes = []any{
	(MakerMessageType)(0),    // 0: marketstream.v1.MakerMessageType
	(RouterMessageType)(0),   // 1: marketstream.v1.RouterMessageType
	(*Heartbeat)(nil),        // 2: marketstream.v1.Heartbeat
	(*PairKey)(nil),          // 3: marketstream.v1.PairKey
	(*PriceLevel)(nil),       // 4: marketstream.v1.PriceLevel
	(*CompactFrame)(nil),     // 5: marketstream.v1.CompactFrame
	(*MarketFrame)(nil),      // 6: marketstream.v1.MarketFrame
	(*MakerEnvelope)(nil),    // 7: marketstream.v1.MakerEnvelope
	(*FrameAck)(nil),         // 8: marketstream.v1.FrameAck
	(*ConnectionAck)(nil),    // 9: marketstream.v1.ConnectionAck
	(*RouterEnvelope)(nil),   // 10: marketstream.v1.RouterEnvelope
	(*Error)(nil),            // 11: marketstream.v1.Error
	(*PairFilter)(nil),       // 12: marketstream.v1.PairFilter
	(*SubscribeRequest)(nil), // 13: marketstream.v1.SubscribeRequest
	(*PairFilterResult)(nil), // 14: marketstream.v1.PairFilterResult
	(*SubscribeAck)(nil),     // 15: marketstream.v1.SubscribeAck
}
var file_marketstream_proto_depIdxs = []int32{
	3,  // 0: marketstream.v1.MarketFrame.pair:type_name -> marketstream.v1.PairKey
	4,  // 1: marketstream.v1.MarketFrame.bids:type_name -> marketstream.v1.PriceLevel
	4,  // 2: marketstream.v1.MarketFrame.asks:type_name -> marketstream.v1.PriceLevel
	5,  // 3: marketstream.v1.MarketFrame.frame:type_name -> marketstream.v1.CompactFrame
	0,  // 4: marketstream.v1.MakerEnvelope.type:type_name -> marketstream.v1.MakerMessageType
	6,  // 5: marketstream.v1.MakerEnvelope.frame_push:type_name -> marketstream.v1.MarketFrame
	8,  // 6: marketstream.v1.MakerEnvelope.frame_ack:type_name -> marketstream.v1.FrameAck
	2,  // 7: marketstream.v1.MakerEnvelope.heartbeat:type_name -> marketstream.v1.Heartbeat
	9,  // 8: marketstream.v1.MakerEnvelope.connection_ack:type_name -> marketstream.v1.ConnectionAck
	3,  // 9: marketstream.v1.FrameAck.pair:type_name -> marketstream.v1.PairKey
	1,  // 10: marketstream.v1.RouterEnvelope.type:type_name -> marketstream.v1.RouterMessageType
	13, // 11: marketstream.v1.RouterEnvelope.subscribe:type_name -> marketstream.v1.SubscribeRequest
	15, // 12: marketstream.v1.RouterEnvelope.subscribe_ack:type_name -> marketstream.v1.SubscribeAck
	6,  // 13: marketstream.v1.RouterEnvelope.update:type_name -> marketstream.v1.MarketFrame
	2,  // 14: marketstream.v1.RouterEnvelope.heartbeat:type_name -> marketstream.v1.Heartbeat
	11, // 15: marketstream.v1.RouterEnvelope.error:type_name -> marketstream.v1.Error
	9,  // 16: marketstream.v1.RouterEnvelope.connection_ack:type_name -> marketstream.v1.ConnectionAck
	3,  // 17: marketstream.v1.PairFilter.pair:type_name -> marketstream.v1.PairKey
	12, // 18: marketstream.v1.SubscribeRequest.filters:type_name -> marketstream.v1.PairFilter
	12, // 19: marketstream.v1.PairFilterResult.filter:type_name -> marketstream.v1.PairFilter
	14, // 20: marketstream.v1.SubscribeAck.results:type_name -> marketstream.v1.PairFilterResult
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_marketstream_proto_init() }
func file_marketstream_proto_init() {
	if File_marketstream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketstream_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PairKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PriceLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CompactFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MarketFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MakerEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FrameAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectionAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RouterEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*PairFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*PairFilterResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketstream_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_marketstream_proto_msgTypes[5].OneofWrappers = []any{
		(*MakerEnvelope_FramePush)(nil),
		(*MakerEnvelope_FrameAck)(nil),
		(*MakerEnvelope_Heartbeat)(nil),
		(*MakerEnvelope_ConnectionAck)(nil),
	}
	file_marketstream_proto_msgTypes[8].OneofWrappers = []any{
		(*RouterEnvelope_Subscribe)(nil),
		(*RouterEnvelope_SubscribeAck)(nil),
		(*RouterEnvelope_Update)(nil),
		(*RouterEnvelope_Heartbeat)(nil),
		(*RouterEnvelope_Error)(nil),
		(*RouterEnvelope_ConnectionAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketstream_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketstream_proto_goTypes,
		DependencyIndexes: file_marketstream_proto_depIdxs,
		EnumInfos:         file_marketstream_proto_enumTypes,
		MessageInfos:      file_marketstream_proto_msgTypes,
	}.Build()
	File_marketstream_proto = out.File
	file_marketstream_proto_rawDesc = nil
	file_marketstream_proto_goTypes = nil
	file_marketstream_proto_depIdxs = nil
}
